apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yaml
images:
  - name: 729231827726.dkr.ecr.us-east-2.amazonaws.com/dev/voyago
    newTag: frontend-6c21c0b6df600eba5c500220733c112846406c0b
